addons:
  chrome: stable
sudo: required
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - develop

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install
script:
  - yarn lint
  - yarn test
  - yarn build






